### PR TITLE
reddit.js: Fixed crash related to no arguments.

### PR DESCRIPTION
**Pull request by gkbrk**

### CODE REVIEW

**Comment by M4GNV5** [comment]
maybe it should output some information like "Usage !reddit <subreddit>" instead of just remaining silent when no arguments are given

**Comment by gkbrk** [comment]
@M4GNV5 Added usage message.

**Comment by M4GNV5** [comment]
without returning it will output that message and then crash :stuck_out_tongue:

**Comment by gkbrk** [comment]
Whoops

**Comment by M4GNV5** [comment]
thanks for the input :)

**Comment by gkbrk** [comment]
No problem

**Pull request merged**
